server:
  port: 8092
spring:
  output:
    ansi:
      enabled: always

asset:
  volatility:
    sigma: 0.02         # 일일 변동성(표준편차)
  clamp:
    min-percent: -5.0    # 일일 최소 변동률(%)
    max-percent: 5.0     # 일일 최대 변동률(%)
  cache:
    zone-id: Asia/Seoul  # 캐시 기준 일자 산정 타임존
  caffeine:
    expire-after-write-days: 1   # 캐시 TTL (일)
    max-size: 300000       # 캐시 최대 엔트리 (DAU 규모에 맞춰 조정)
    record-stats: true         # 히트율 등 통계 수집 여부