name: Deploy Extension Server

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ext-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    if: github.event_name != 'workflow_dispatch' && contains(github.event.head_commit.message, 'deploy') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ext-server
      TARGET_PLATFORM: linux/arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./dg-extension-server
          platforms: ${{ env.TARGET_PLATFORM }}
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.RPI_SSH_KEY }}

      - name: Debug DNS Resolution
        run: |
          echo "Attempting to resolve ${{ secrets.RPI_HOST }}"
          nslookup ${{ secrets.RPI_HOST }} || true

      - name: Add Raspberry Pi host key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.RPI_HOST_KEY }}" >> ~/.ssh/known_hosts

      - name: Deploy to Raspberry Pi
        env:
          RPI_HOST: ${{ secrets.RPI_HOST }}
          RPI_USER: ${{ secrets.RPI_USER }}
          RPI_SSH_PORT: ${{ secrets.RPI_SSH_PORT }}
          GITHUB_SHA: ${{ github.sha }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        run: |
          set -e
          docker save ${IMAGE_NAME}:${GITHUB_SHA} \
          | ssh -p ${RPI_SSH_PORT} ${RPI_USER}@${RPI_HOST} 'docker load'

          ssh -p ${RPI_SSH_PORT} ${RPI_USER}@${RPI_HOST} <<EOSSH
          set -e
          docker tag ext-server:${GITHUB_SHA} ext-server:current
          # auth가 healthy인 상태에서 ext만 교체 기동
          docker compose -f /home/phs/dgb/compose/docker-compose.yml up -d --force-recreate --no-deps ext
          EOSSH

      # /actuator/health
      # 아래 의존성 build.gradle에 필요
      # implementation 'org.springframework.boot:spring-boot-starter-actuator'
      - name: Smoke test (ext health on localhost)
        if: success()
        env:
          RPI_USER: ${{ secrets.RPI_USER }}
          RPI_HOST: ${{ secrets.RPI_HOST }}
          RPI_SSH_PORT: ${{ secrets.RPI_SSH_PORT }}
        run: |
          set -e
          ssh -p "${RPI_SSH_PORT}" "${RPI_USER}@${RPI_HOST}" 'bash -seuo pipefail' <<'EOSSH'
            echo "--- Smoke test (localhost:8092/actuator/health) ---"
            # 최대 60초 동안 재시도: 12회 x 5초
            body=$(curl -fsS \
              --retry 12 --retry-all-errors --retry-delay 5 \
              --connect-timeout 3 --max-time 10 \
              http://localhost:8092/actuator/health) || { echo "FAIL: cannot reach ext"; exit 1; }

            # Spring Boot Actuator 형식(status=UP) 확인
            if echo "$body" | grep -q '"status"\s*:\s*"UP"'; then
              echo "PASS: ext actuator reports UP."
              exit 0
            fi

            # (옵션) 액추에이터를 안 쓰면 /ping 같은 경량 엔드포인트로 대체도 가능
            # status=$(curl -s -o /dev/null -w '%{http_code}' http://localhost:8092/ping || true)
            # [ "$status" -eq 200 ] && { echo "PASS: /ping reachable."; exit 0; }

            echo "FAIL: actuator reachable but not UP. Response was: $body"
            exit 1
          EOSSH

      - name: Collect remote logs on failure
        if: failure()
        env:
          RPI_USER: ${{ secrets.RPI_USER }}
          RPI_HOST: ${{ secrets.RPI_HOST }}
          RPI_SSH_PORT: ${{ secrets.RPI_SSH_PORT }}
        run: |
          ssh -p ${RPI_SSH_PORT} ${RPI_USER}@${RPI_HOST} <<'EOSSH'
            set +e
            echo "===== [compose ps] 현재 서비스 상태 ====="
            cd /home/phs/dgb/compose && docker compose ps
            echo
            echo "===== [compose logs] ext 최근 200줄 ====="
            docker compose logs --tail=200 ext
            echo
            echo "===== [docker ps -a] 최근 컨테이너 목록 ====="
            docker ps -a --format "table {{.ID}}\t{{.Image}}\t{{.Status}}\t{{.Names}}" | head -n 20
            echo
            echo "===== [system df] 도커 디스크 사용량 ====="
            docker system df
          EOSSH

      - name: Remote disk cleanup (Docker images)
        if: always()
        env:
          RPI_USER: ${{ secrets.RPI_USER }}
          RPI_HOST: ${{ secrets.RPI_HOST }}
          RPI_SSH_PORT: ${{ secrets.RPI_SSH_PORT }}
        run: |
          ssh -p ${RPI_SSH_PORT} ${RPI_USER}@${RPI_HOST} <<'EOSSH'
          set -e
          echo "===== [BEFORE] docker system df ====="
          docker system df || true
          echo
          docker image prune -f || true
          docker image prune -a -f --filter "until=168h" || true
          echo
          echo "===== [AFTER] docker system df ====="
          docker system df || true
          EOSSH
